const assert = require('node:assert/strict');
const { mkdtemp, readFile, stat, mkdir, rm } = require('node:fs/promises');
const { join } = require('node:path');
const { tmpdir } = require('node:os');
const create = require('../electron/demo-recorder.cjs');
(async () => {
  const home = await mkdtemp(join(tmpdir(), 'kindred-recorder-'));
  let captures = 0;
  const recorder = create({ isDestroyed: () => false, webContents: { capturePage: async () => { captures++; return { toJPEG: () => Buffer.from('synthetic-frame') }; } } }, home);
  await recorder.start();
  await assert.rejects(recorder.start(), /already active/);
  await new Promise(r => setTimeout(r, 550));
  const result = await recorder.stop();
  const manifest = JSON.parse(await readFile(join(result.directory, 'recording.json'), 'utf8'));
  assert.ok(captures >= 3);
  assert.equal(manifest.audio, false);
  assert.equal(manifest.captureErrors, 0);
  assert.ok(manifest.frames.every((f,i,a) => !i || f.elapsed >= a[i-1].elapsed));
  assert.equal((await stat(join(result.directory, manifest.frames[0].name))).mode & 0o777, 0o600);
  await assert.rejects(recorder.stop(), /No recording/);
  await recorder.start();
  const { readdir } = require('node:fs/promises');
  const dirs = await readdir(join(home, 'recordings'));
  const directory = join(home, 'recordings', dirs.sort().at(-1));
  await mkdir(join(directory, 'recording.json'));
  const failed = await recorder.stop();
  assert.equal(failed.recording, false);
  assert.ok(failed.saveError);
  await rm(join(directory, 'recording.json'), { recursive: true });
  const retried = await recorder.retrySave();
  assert.equal(retried.saveError, undefined);
  assert.ok(JSON.parse(await readFile(join(directory, 'recording.json'))).frames.length);
  console.log(JSON.stringify({ name: 'recorder manifest failure retains frames and retry metadata', passed: true }));
  let failCapture = false;
  const captureFailure = create({ isDestroyed: () => false, webContents: { capturePage: async () => { if (failCapture) throw Error('synthetic capture failure'); return { toJPEG: () => Buffer.from('frame') }; } } }, home);
  await captureFailure.start(); failCapture = true;
  const partial = await captureFailure.stop();
  assert.equal(partial.recording, false); assert.equal(partial.captureErrors, 1);
  assert.equal(partial.saveError, undefined);
  console.log(JSON.stringify({ name: 'recorder final capture failure stops safely and saves partial frames', passed: true }));
  console.log(JSON.stringify({ name: 'app-only recorder serial frames, lifecycle and private files', passed: true, frames: captures }));
})().catch(e => { console.error(e); process.exitCode=1; });
