import {chromium} from '../booking-staging/node_modules/@playwright/test/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('video',{recursive:true});
const browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'video',size:{width:1440,height:1000}},acceptDownloads:true});
const page=await context.newPage();
await page.goto('http://127.0.0.1:4190');
await page.waitForTimeout(3000);
await page.getByRole('button',{name:'← Open local workspace'}).click();
await page.getByRole('textbox').fill('Design a calm, mobile-first treatment booking app with five screens: services, treatment details, date and slots, contact details and confirmation.');
await page.waitForTimeout(4500);
await page.getByRole('button',{name:'Load sample',exact:true}).nth(0).click();
await page.waitForTimeout(5000);
await page.getByRole('button',{name:'More project actions'}).click();
await page.waitForTimeout(2500);
await page.getByRole('menuitem',{name:'Open preview'}).click();
await page.waitForTimeout(2500);
await page.getByRole('combobox',{name:'Screen',exact:true}).selectOption('2');
await page.waitForTimeout(2500);
await page.getByRole('combobox',{name:'Screen',exact:true}).selectOption('4');
await page.waitForTimeout(2500);
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('textbox').fill('Make the booking button more prominent and use warmer colours.');
await page.getByRole('textbox').scrollIntoViewIfNeeded();
await page.waitForTimeout(4000);
await page.getByRole('button',{name:'More project actions'}).click();
await page.waitForTimeout(2500);
const downloadEvent=page.waitForEvent('download');
await page.getByRole('menuitem',{name:'Export code'}).click();
const download=await downloadEvent;await download.saveAs('video/kindred-recorded-export.zip');
await page.waitForTimeout(3500);
await page.getByRole('heading',{name:'Treatment Booking',exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:'video/poster.png'});
await page.waitForTimeout(2500);
const video=page.video();await context.close();await video.saveAs('video/studio-walkthrough.webm');await browser.close();
await writeFile('video/README.md','Actual local browser recording. Authored samples, static proposal previews and ZIP export. No ChatGPT sign-in, AI generation or applied refinement is shown; the refinement prompt is entered while generation remains disabled. No real bookings.\n');
console.log('Recording saved to video/studio-walkthrough.webm');
